### ISSUE TITLE
Manual Analysis error with ruProcess() ; prcomp.default(df, center = T, scale = T)

### ISSUE THREAD

**Issue by MargoKapustina** [kaitsull/RUHi#2]
When using the the ruProcess() function in the manual analysis pipeline, I would get the following error after an automated run through FIJI:

```r
myobj <- ruProcess(myobj))
#Error in prcomp.default(df, center = T, scale = T) :
#cannot rescale a constant/zero column to unit variance
```

To solve this, I checked that all channels from my mFISH experiment had non-zero levels of expression. In my 12-probe experiment, my T7 was empty and thus had no signal. Removing the T7 file from the '/NonLinearReg' folder and re-running the RUHi pipeline resolved this issue.

**Comment by kaitsull** [comment]
Awesome thanks for posting this helpful hint Margo!

Another way you can fix this error is to use:
myobj <- ruFilter(myobj, exclude = "T7")
